# Generated by Django 2.0.7 on 2018-11-24 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weCheck', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('result', models.CharField(max_length=100)),
                ('reMsg', models.CharField(max_length=100)),
                ('checkId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weCheck.check')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weCheck.user')),
            ],
        ),
    ]
