# Generated by Django 2.1 on 2018-08-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weCheck', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='checkplan',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='userType',
            field=models.IntegerField(),
        ),
    ]
