# Generated by Django 2.0.7 on 2018-11-26 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weCheck', '0002_leave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='checkId',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='username',
        ),
        migrations.DeleteModel(
            name='leave',
        ),
    ]
