# Generated by Django 2.0.7 on 2018-11-29 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weCheck', '0002_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
